# Nombre de la action
name: Build container and run VISE API testing

# Bajo qué acción se va a ejecutar la action (manual en este caso)
on:
  workflow_dispatch:

# Tareas a ejecutar
jobs:
  test:
    # SO de la máquina virtual
    runs-on: ubuntu-latest

    steps:
      # Descargar el código del repositorio
      - name: Checkout repository
        uses: actions/checkout@v4

      # Instalar docker
      - name: Setup docker
        uses: docker/setup-buildx-action@v3

      # Construir imagen de docker
      - name: Build docker image
        run: |
          docker build -t vise-api:latest .

      # Levantar contenedor
      - name: Run container
        run: |
          # Eliminar contenedor viejo si existe
          docker rm -f vise-api || true
          
          # Levantar nuevo contenedor en puerto 8000
          docker run -d -p 8000:8000 --name vise-api vise-api:latest
          sleep 5

      # Instalar hurl
      - name: Setup hurl (API testing tool)
        uses: gacts/install-hurl@v1

      # Ejecutar pruebas de API
      - name: Test API
        run: hurl --variable host=http://localhost:8000 \
                  --error-format long --test session.hurl
